### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by michlis** [jtwig/jtwig#232]
Hi,
Please provide build instructions* or consider setting up continues integration server for JTwig to have nightly builds available.

*) When trying to build it locally I have broken dependency for com.google.common.base.Function in jtwig / jtwig-functions / src / main / java / com / lyncode / jtwig / functions / json / JsonMapperProvider.java

**Comment by lyncodev** [comment]
Jtwig is now using (CR) continuous releasing. Check https://github.com/jtwig/jtwig.
