### ISSUE TITLE
[solved] JTwig 3 without SpringMVC

### ISSUE THREAD

**Issue by tgart** [jtwig/jtwig#266]
Hi, I have a question for you. Is the new version JTwig can operate without SpingMVC? My application runs on pure REST. Wants to migrate from version JTwig 2 to 3. On Github is an example only for version 2. Now i use like: https://github.com/jtwig/jtwig-examples/tree/master/simple-app

**Comment by realcnbs** [comment]
Of course, just don't include jtwig-spring in your pom. And use jtwig pragmatically.

**Comment by tgart** [comment]
Thanks! my mistake, it works!

**Comment by thomas-p-wilson** [comment]
Closing the matter at the behest of @tgart.
