### ISSUE TITLE
Can't set variable in extending template

### ISSUE THREAD

**Issue by domistiller** [jtwig/jtwig#273]
I can't put other tags (I tried set and if/endif) in a template which uses "extends". I tried the following code:
```twig
{# layout.twig #}
{{ variable }}
{% block content %}
   
{% endblock %}
```
```twig
{# home.twig #}
{% extends "layout.twig" %}
{% set variable = "Test" %}

{% block content %}
   Content
{% endblock %}
```

It works in the PHP Twig, but not in JTwig.
I either get `Wrong extends syntax Explanation: Input position (line 1, pos 12): {% extends "layout.twig" %} ^` or `Unknown tag Explanation: Input position (line 2, pos 4): {% extends "layout.twig" %} ^`, depending on where I put the set statement.

**Comment by thomas-p-wilson** [comment]
Thanks for the feedback @domistiller. What version of Jtwig are you using?

**Comment by domistiller** [comment]
I am using Version 3.1.1

**Comment by thomas-p-wilson** [comment]
That fits. This matter was resolved in PR #154 which is in master and slated to be released for 4.0.0

**Comment by domistiller** [comment]
Thanks :)

**Comment by sallypang** [comment]
I'm having the same problem. Sorry, so it's not fixable at the moment?
