### ISSUE TITLE
Function render doesn't work

### ISSUE THREAD

**Issue by amossoma** [jtwig/jtwig#284]
I didn't find combination of spring, java, conatiner which would work. Maybe it's problem with servlet version, or spring version. I don't know. I'm going to rewrite it using xnio, and add parameter "timeout".

**Comment by lyncodev** [comment]
Hi @amossoma,

can you provide the Spring and Servlet api version you are using?

**Comment by amossoma** [comment]
I tried Spring 3.0.5 with tomcat 7, Spring 4 with Undertow and current version Spring Boot.
I think the problem is with method "isAsyncStarted()", which doesn't exist:

java.lang.AbstractMethodError: com.lyncode.jtwig.util.render.RenderHttpServletRequest.isAsyncStarted()Z
	javax.servlet.ServletRequestWrapper.isAsyncStarted(ServletRequestWrapper.java:390)
	com.lyncode.jtwig.functions.SpringFunctions.render(SpringFunctions.java:99)
	com.lyncode.jtwig.functions.SpringFunctions.render(SpringFunctions.java:83)
	sun.reflect.GeneratedMethodAccessor27.invoke(Unknown Source)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:606)
	com.lyncode.jtwig.functions.resolver.model.Executable.execute(Executable.java:31)
	com.lyncode.jtwig.render.RenderContext.executeFunction(RenderContext.java:138)
	com.lyncode.jtwig.expressions.model.FunctionElement$Compiled.calculate(FunctionElement.java:80)
	com.lyncode.jtwig.content.model.compilable.Output$Compiled.render(Output.java:52)
	com.lyncode.jtwig.content.model.compilable.Sequence$Compiled.render(Sequence.java:80)
	com.lyncode.jtwig.parser.JtwigParser$CompiledDocument.render(JtwigParser.java:67)
	com.lyncode.jtwig.mvc.JtwigView.renderMergedTemplateModel(JtwigView.java:100)
	org.springframework.web.servlet.view.AbstractTemplateView.renderMergedOutputModel(AbstractTemplateView.java:167)
	org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:250)
	org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1047)
	org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:817)
	org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:719)
	org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:644)
	org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:549)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)

**Comment by amossoma** [comment]
By the way, I have been talking to you, about one year ago, and at long last I have time and permission from my company to participate in your project. So if you want some help I'm ready :)

**Comment by lyncodev** [comment]
@amossoma everyone is very welcome to join! An easy way to start with is looking at some issues/feature requests and implementing it.

jtwig-tech-list@googlegroups.com is a nice place to shout your doubts.

**Comment by thomas-p-wilson** [comment]
@amossoma, feel free to shoot me a message if you have any questions or
issues.

**Comment by invik** [comment]
I have the same issue but with jetty (version 9.2.9.v20150224)
From what I saw, it is because jTwig is not Servlet API 3.0 compatible which is needed for webapps without web.xml

**Comment by invik** [comment]
I have submitted a pull request for this issue: https://github.com/jtwig/jtwig/pull/291
Please, feel free to report to me any problem you may find.
On my project, render is now ok with no major issue expect for debug log messages on RenderHttpServletResponse

**Comment by lyncodev** [comment]
There is a working example here https://github.com/jtwig/jtwig-examples/tree/master/gradle-jtwig-render-extension-simple.
