### ISSUE TITLE
Standalone template population

### ISSUE THREAD

**Issue by farannegarestan** [jtwig/jtwig#285]
I wish there was a feature to populate a template and give out a string to send as an email. I had to resort to Velocity for that purpose while all my front end is using jtwig. Do you have anything under development for that or I can work on it.

**Comment by lyncodev** [comment]
Hi @farannegarestan,

I've used Jtwig for that purpose before. Check this related example:

https://github.com/jtwig/jtwig-examples/blob/master/simple-app/src/main/java/com/lyncode/jtwig/example/Sample.java

**Comment by farannegarestan** [comment]
That's awesome! Thanks!

**Comment by realcnbs** [comment]
That example won't compile in latest versions.

```
Map<String, String> resources = new HashMap<>();

// ... populate resources map with template file paths and names

MapJtwigResource resource = new MapJtwigResource("tmpl.html.twig", resources);
JtwigTemplate tmpl = new JtwigTemplate(resource, new JtwigConfiguration());

JtwigModelMap modelMap = new JtwigModelMap();
modelMap.put("someVar", "someVarValue");

String out = tmpl.output(modelMap);
```

**Comment by lyncodev** [comment]
@realcnbs Is MapJtwigResource part of 3.1.1?

**Comment by EvSpirit** [comment]
It seems the example mentioned above won't work cause there is no JtwigContext in 3.1.1. Do you have any up-to-date example?

**Comment by realcnbs** [comment]
@lyncodev Not sure, i am on snapshot always :)

**Comment by realcnbs** [comment]
@EvSpirit check my comment for working version.

**Comment by EvSpirit** [comment]
@realcnbs , thanks a lot! But I'm on 3.1.1 and there is no MapJtwigResource as @lyncodev said before. I'm migration from 2.1.x (huh!) so I have to look into some sources :)

**Comment by realcnbs** [comment]
@EvSpirit well, you could just copy paste it to your project and use, in case you need an in memory resource

**Comment by lyncodev** [comment]
Example with the current API for 4.x https://github.com/jtwig/jtwig-examples/blob/master/simpleapp-jtwig-4.x/src/main/java/org/jtwig/example/SimpleApp.java

**Comment by thomas-p-wilson** [comment]
Is this still open for discussion? Or should the ticket be closed?
