### ISSUE TITLE
Support map entry syntax throughout expressions

### ISSUE THREAD

**Issue by thomas-p-wilson** [jtwig/jtwig#288]
Presently, the (map entry|array index|attribute) syntax `var[0]` only works for just that format, where the first token is a variable, followed by the attribute syntax. This needs to be amended such that the following examples work:

- `[0,1,2][1]` => `1`
- `'test'|split[1]` => 'e'

**Comment by lyncodev** [comment]
Supported in the new version (https://github.com/jtwig/jtwig-core/blob/master/src/test/java/org/jtwig/integration/issues/Issue288Test.java)
