### ISSUE TITLE
Structured Layouts - ability to use absolute paths

### ISSUE THREAD

**Issue by rezu88** [jtwig/jtwig#294]
In big projects there is a need to split templates files into hierarchical tree. When a template is located deep, using layout results in instruction similar to:
{% extends '../../../layouts/main.twig' %}

I would love to have an option to use absolute paths such us:
{% extends '/layouts/main.twig' %}
which is also resistant from moving template up or down the directory hierarchy..

**Comment by thomas-p-wilson** [comment]
A quick test of Twig shows that Twig supports what you are proposing.
Namely, files prepended with a slash are treated as absolute locations,
while those lacking the slash prefix are treated as relative paths. I will
move forward with implementation.

The only thing to note is that, while this will work for filesystem-based
resources, it may or may not work for classpath-loaded resources. I will
have to look into that a little further after initial implementation.

Thanks for your feedback!

**Comment by lyncodev** [comment]
Supported in the new version (https://github.com/jtwig/jtwig-core/blob/master/src/test/java/org/jtwig/integration/issues/Issue294Test.java)
