### ISSUE TITLE
Wrong output syntax in Syntatic Symbols 

### ISSUE THREAD

**Issue by gazatem** [jtwig/jtwig#302]
I'm receiving Wrong output syntax error when avoiding Javascript syntax.

    <# extends "layout/base.twig.html" #>
    <# block content #>
    Welcome to  <@ name @>
    <# endblock #>

If I try to use <@ name @> syntax to output a variable, template engine can not parse the template. If I remove variable, there is no error.

**Comment by babs** [comment]
Isn't it {{ name }} ?

**Comment by thomas-p-wilson** [comment]
Apologies @kemalyenilmez for the tardy reply. Assuming you're using the built-in javascript-collision-free tags, you need to reverse your output such that you end up with `@> name <@`. Otherwise everything looks good. Let me know if this fails to resolve your issue or if you need anything else.
