### ISSUE TITLE
UTF8 file on Windows

### ISSUE THREAD

**Issue by jmsanzg** [jtwig/jtwig#304]
Platform: Windows
JTwig version: 3.1.1

Problem: if .twig files are UTF8 encoded, when loaded, you can see some symbols instead of the desired special character. For instance, if the file contains the word "Artículos" when parsed that word will be transformed to "ArtÄóculos".

In my case I've been able to bypass this by setting the -Dfile.encoding=UTF8 argument when starting the JVM but there may be some other people without that being an available option.

The problem is located here https://github.com/jtwig/jtwig/blob/fad5332398928b169b00b8a0c09a63af75edb9eb/jtwig-core/src/main/java/org/jtwig/Environment.java#L100 because you're making use of Charset.defaultCharset() . In my case, the default charset is Latin1 (ISO-8859-1) because I'm at Spain but I want to make things more I18N than that and that's why I'm using UTF-8 on my whole project.

To fix this I'd add a new encoding attribute inside JtwigConfiguration defaulted to Charset.defaultCharset() that allows to define other Encodings like UTF-8.

**Comment by jampajeen** [comment]
Is it fixed?

**Comment by jmsanzg** [comment]
Not as far as I know. I changed the template framework and started to use Pebble, far better than JTwig (at leadt tó me) It has the same problem but I made a patch and released on versión 2.0.0 (https://github.com/PebbleTemplates/pebble )

**Comment by lyncodev** [comment]
This has been added to the new version. You just need to provide the default input charset.
http://jtwig.org/documentation/reference/core/environment#resources. You can also check the test created to reproduce the issue: https://github.com/jtwig/jtwig-core/blob/master/src/test/java/org/jtwig/integration/issues/Issue304Test.java
