### ISSUE TITLE
Confusing caching setting in jtwig-spring

### ISSUE THREAD

**Issue by katafractari** [jtwig/jtwig#305]
To completely disable caching of templates, JtwigViewResolver.setCache(false) was not enough so I had to do this:
![snippet](https://cloud.githubusercontent.com/assets/1299228/10388366/941d2d4e-6e69-11e5-912b-16a2631d1012.png)

I didn't thoroughly go through the jTwig code so I don't have a full overview of what's happening but I did notice that decision to pull a template from cache is actually based on two settings, one is AbstractCachingViewResolver.cacheLimit and the other one is JtwigViewResolver.cached.

**Comment by jpolete** [comment]
Thanks for pointing that out @katafractari . I found the caching was broken too, but I hadn't opened an issue yet. Using both setCache and the deprecated setCached does work.

**Comment by lyncodev** [comment]
To make things clear, the cache configuration was moved away from the view resolver configuration. The deprecated code was also removed. Note that Spring view resolver cache mechanism (``ViewResolver::setCache``) is a distinct concept when compared to the Jtwig template caching. 

Spring View Resolver cache just speeds up the view resolution (check http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/servlet/view/AbstractCachingViewResolver.html), which can be really useful when, for example, using multiple view resolvers. 

Jtwig cache is about caching parsed templates (check the parser configuration http://jtwig.org/documentation/reference/core/environment#parser - TemplateCache property)
