### ISSUE TITLE
Need documentation for non-Spring integration

### ISSUE THREAD

**Issue by nanodeath** [jtwig/jtwig#306]
The [Getting Started](http://jtwig.org/documentation/get-started/) page only mentions Spring integration, but it seems like jtwig can also be used outside of Spring. I spent half an hour yesterday trying to get the `jtwig` artifact to work (as opposed to `jtwig-spring`), but it appears that was the wrong approach. Do I need to add a dependency on `jtwig-core`? What about `jtwig-functions` and `jtwig-types`?

**Comment by lyncodev** [comment]
There is some references:
http://jtwig.org/documentation/quick-start/application
http://jtwig.org/documentation/reference/core/integration
https://github.com/jtwig/jtwig-examples
