### ISSUE TITLE
Build anchor link within spring application

### ISSUE THREAD

**Issue by fritzfs** [jtwig/jtwig#308]
Hi!

Is there a better way to build full link instead of this?

`<td><a href="{{ '' | path}}/terminal/read/{{ item.id }}">{{ item.id }}</a></td>`

It's a shame this doesn't work:

`<td><a href="{{ /terminal/read/{{ item.id }} | path }}">{{ item.id }}</a></td>`

Update:

Perhaps this on top?

`{% set url = '' | path %}`

And later just this:

`<td><a href="{{ url }}/terminal/read/{{ item.id }}">{{ item.id }}</a></td>`

**Comment by thomas-p-wilson** [comment]
Jtwig is intended to be syntactically equivalent to Twig. Jtwig does support concatenation in the same way Twig does, so you should be able to do something like:
```
<td><a href="{{ '/terminal/read/'~item.id | path }}">{{ item.id }}</a></td>
```
That's off the top of my head, but should at least point in the right direction.

The reason `<td><a href="{{ /terminal/read/{{ item.id }} | path }}">{{ item.id }}</a></td>` doesn't work is that Twig syntax doesn't support nesting output braces as you've done with your inner `{{ item.id }}`. You'd need to concatenate that as part of your string instead, as I've demonstrated above.

r/Thomas

**Comment by fritzfs** [comment]
Thomas,

it seems that jtwig doesn't support string concate (at least using ~). For every try I get syntax error.

Can you confirm this?

Going further, it seems if I wish to remove set url line I could combine format with path like this:

`<a href="{{ 'terminal/read/%d' | format(item.id) | path }}">{{ item.id }}</a>`
