### ISSUE TITLE
TagAddon changes string for Cp858 Charset

### ISSUE THREAD

**Issue by tobiascapin** [jtwig/jtwig#310]
I tried to set a "void" TagAddon to my Jtwig parser:

```
public class VoidEscape extends TagAddon {
    public VoidEscape(JtwigResource resource, 
        ParserConfiguration configuration) {
        super(resource, configuration);
    }

    @Override
    protected com.google.common.base.Function<java.lang.String, java.lang.String> transformation() {
        return new Function<String, String>() {
            @Override
            public String apply(String input) {
            	return input;
            }
        };
    }

    @Override
    protected String keyword() {
        return "void";
    }
}
```

Therefore I set two field in the template, one with Void function and the other without it:

```
Voided: {% void %}{{string}}{% endvoid %}
Plain: {{string}}
```

Next, I exported this render with Charset Cp858

`jtwigConfig.render().charset(Charset.forName("Cp858"));`

The result is that the two lines are not the same!!

In my example with "The è" as input I got:

> Voided: The ï¿½(wrong encoding)
> Plain: The Š (right encoding)

**Comment by lyncodev** [comment]
The test recreating the issue can be found here https://github.com/jtwig/jtwig-core/blob/431515e884898b41c72f73883127de5ec0cf49ab/src/test/java/org/jtwig/integration/issues/Issue310Test.java . It has now been fixed. Thanks @tobiascapin
