### ISSUE TITLE
Problem with JTwig Spring and resolving relative paths.

### ISSUE THREAD

**Issue by rikschennink** [jtwig/jtwig#313]
Hi, We're trying to setup jtwig and the node version of twig. Relative paths work correctly in the node version but we're running into trouble when using relative paths in jtwig.

We've tried with this example: 
https://github.com/jtwig/jtwig-examples/tree/master/gradle-jtwig-spring-simple

While the initial template renders fine, when adding an include or embed with a relative path e.g. './_partials/menu.twig' Twig cannot find the partial.

Are we missing something obvious? A configuration parameter maybe?

**Comment by lyncodev** [comment]
Hi @rikschennink try with ``_partials/menu.twig``

**Comment by lyncodev** [comment]
@rikschennink I wasn't able to reproduce the issue. The test https://github.com/lyncodev/jtwig-core/blob/master/src/test/java/org/jtwig/integration/issues/Issue313Test.java passes. Maybe there is something wrong in the location of the partial.

**Comment by rikschennink** [comment]
Thanks! Good to know it should work. It's probably something in our configuration then.

**Comment by kennycason** [comment]
@rikschennink Did you manage to solve this? I am only able to get absolute paths to load. Relative paths are not loading for me. The doc doesn't go into enough detail on how to configure it. This is the last thing I need to get this fully integrated. :)

**Comment by kennycason** [comment]
@rikschennink Thanks for the response! I'll looked into that. Surprisingly, I've had this issue with every template engine I've tried over the last week with the only exception being Handlebars.
