### ISSUE TITLE
JtwigModel Builder Improvements

### ISSUE THREAD

**Issue by facundofarias** [jtwig/jtwig#318]
Hello there!

I am using Jtwig for the very first time, and it is quite okay! The only thing, is while using the JtwigModel Builder (which is quite convenient), it would be awesome if we would be able to set a Map directly. Is that possible?
Cheers!
Thanks.

**Comment by lyncodev** [comment]
Hi @facundofarias thanks for pointing this out. Added an utility method to help wih this.
Check the example in the following test [JtwigModelTest.java](https://github.com/jtwig/jtwig-core/blob/master/src/test/java/org/jtwig/JtwigModelTest.java).

Version is now published, check the most recent versions in [here](https://github.com/jtwig/jtwig).

**Comment by facundofarias** [comment]
@lyncodev Awesome! Thanks

**Comment by facundofarias** [comment]
@lyncodev May I also ask for toString() methods on, for example the JtwigModel objects? It helps a lot while debugging. Thanks!

**Comment by lyncodev** [comment]
Hi @facundofarias, it's not good idea to create code just for debugging purposes, code in Jtwig needs to have a functional reason.
