### ISSUE TITLE
For loops

### ISSUE THREAD

**Issue by PieerotGG** [jtwig/jtwig#319]
Hello,
Is there an equivalent of:
`for(int i = 0; i < 10 ; i++){}`
in Jtwig ?

Thank you very much for your support !

**Comment by lyncodev** [comment]
Hi @PieerotGG, yes there is.

```twig
{% for i in [0..9] %}
{% endfor %}
```

Documentation [here](http://jtwig.org/documentation/reference/tags/control-flow#for-loops)
