### ISSUE TITLE
Round filter not supported?

### ISSUE THREAD

**Issue by rikschennink** [jtwig/jtwig#321]
This is the round filter in Twig: http://twig.sensiolabs.org/doc/filters/round.html

I was trying to use it in jTwig but it did not work
```
{{ 42.55|round(1, 'floor') }}
```
Throws `Function round error: Expected at most 2 arguments`

Turns out jTwig has a round function `round(42.55, 'floor')` but it does not support the precision parameter. Would be great if this was somewhat the same.

Any plans on adding the filter version of round?

**Comment by lyncodev** [comment]
Hi @rikschennink,

it doesn't look very hard to do. It would only require changes in the [RoundFunction.java](https://github.com/jtwig/jtwig-core/blob/e0598b1885284375062fed75ceeaaabe605fa3aa/src/main/java/org/jtwig/functions/impl/math/RoundFunction.java). 

Looking for some spare time to add it in the next few weeks, unless someone help us with a pull request 😃

**Comment by rikschennink** [comment]
That would be great! Thanks :-)

I've got zero experience writing Java so don't feel confident enough to do the changes myself.

**Comment by lyncodev** [comment]
Will be out in next release.
