### ISSUE TITLE
Global Model option

### ISSUE THREAD

**Issue by MakerTim** [jtwig/jtwig#322]
I am working on a PR for this, but to have it linked to a issue

Twig has the simple option to have Global variables
> a  variable that is used in EVERY page

Common usage for me is the google adsense key, footer
things like that you want on every page, a variable that can change, but is global to all pages

http://symfony.com/doc/current/templating/global_variables.html

So i figure, instead of making a new hashmap every JTwigModel
making a copy of a global one
https://github.com/jtwig/jtwig-core/blob/master/src/main/java/org/jtwig/JtwigModel.java#L24

but then te question, backward compatibilty?
so i make first a Model, then add a global. add it to all globals?
or leave the old models like they are?

**Comment by lyncodev** [comment]
Hi @MakerTim,

the concept of global state can be achieved by an application by other means also. But worth seeing your proposal first and discuss on top of it. Backward compatibility would be ideal, if possible making the Jtwig model generation configurable and having it defaulting to the current way of doing it.

We can then think of changing it in the future.

**Comment by janoszen** [comment]
@MakerTim as far as I can tell, the feature you are referencing is implemented by Symfony, not Twig.  Twig gives global variable access only to extensions, not directly to models and Symfony uses an extension to "hack" global variables in place.

**Comment by MakerTim** [comment]
I noticed. 
I tried to replicate the behavior but was failing in the process to do

so my question back is: do you still want it? or say na thx

**Comment by janoszen** [comment]
I'm not the project dev, @lyncodev is. I just shared the info. :)

**Comment by lyncodev** [comment]
@MakerTim every contribution is welcomed. If you can come up with a proposal I would be happy to work with you on it.

**Comment by kashike** [comment]
I'm working on moving a PHP-based web application that uses Symfony and Twig to a Java-based web application that uses Spring and Jtwig, but this is something that's blocking that. Is there a known solution to this issue?

**Comment by MakerTim** [comment]
I did the code for it a long time ago,
but was it was a memory leak in the longlong run

i could submit it as pr, and someone fixes it

**Comment by joao-de-melo** [comment]
Hi Tim, I would be interested to see how you approached it!
