### ISSUE TITLE
NPE in VariableMethodPropertyResolverStrategy since 5.66

### ISSUE THREAD

**Issue by cjbrooks12** [jtwig/jtwig#328]
I've been using JTwig 5.65 for some time now with no issue. I recently updated the version of Jtwig-Core and started to get crashes (nothing else had changed between runs). After some digging, here's what I was able to determine:

- The crash happens when I update Jtwig-Core from 5.65 to 5.66
- Here's a gist of the stack trace: https://gist.github.com/cjbrooks12/c25afa116b8bbd59849c4c70628129de
- From 5.65 to 5.66, Jtwig-Reflection updated from 1.16 to 1.17 (may be related)

The following line will crash:
`{% if index and index.classes and index.classes.internal %}`

while the following will not:
`{% if index and index.classes %}`

I know that `index.classes` is not defined, and before I was able to assume that `if` statements would short-circuit (so if `index.classes` is undefined the entire clause becomes false, so any later checks are unnecessary, thus no attempt to read from an undefined property would occur), but it seems like that behavior has changed.

**Comment by lyncodev** [comment]
@cjbrooks12 thanks for raising it. That's a regression, fixing it ASAP.

**Comment by lyncodev** [comment]
Fixed in version 5.75 (jtwig-core)
