### ISSUE TITLE
Invalid POM for jtwig-spring-boot-starter-5.85.0.RELEASE

### ISSUE THREAD

**Issue by o-nix** [jtwig/jtwig#329]
https://bintray.com/jtwig/maven/download_file?file_path=org%2Fjtwig%2Fjtwig-spring-boot-starter%2F5.85.0.RELEASE%2Fjtwig-spring-boot-starter-5.85.0.RELEASE.pom

    <artifactId>jtwig-spring-boot-starter</artifactId>
    <artifactId>jtwig-spring-boot-starter</artifactId>

````
FAILURE: Build failed with an exception.

* What went wrong:
java.lang.NullPointerException (no error message)

* Exception is:
java.lang.NullPointerException
        at io.spring.gradle.dependencymanagement.internal.maven.MavenPomResolver.createPom(MavenPomResolver.java:113)
        at io.spring.gradle.dependencymanagement.internal.maven.MavenPomResolver.createPoms(MavenPomResolver.java:106)
...
````

5.83 works though.

**Comment by lyncodev** [comment]
There was an issue with the pom's published in jcenter. It has been fixed.
