### ISSUE TITLE
Autoescape escapes everything

### ISSUE THREAD

**Issue by janoszen** [jtwig/jtwig#332]
The autoescape block escapes everything, even template content. It should only escape variables.

**Comment by lyncodev** [comment]
Thanks for pointing out, confirmed as a compatibility issue.

**Comment by lyncodev** [comment]
https://github.com/twigphp/Twig/blob/2.x/lib/Twig/NodeVisitor/Escaper.php

**Comment by lyncodev** [comment]
Fixed in version [5.85.3.RELEASE](https://github.com/jtwig/jtwig/releases/tag/5.85.3.RELEASE)

**Comment by janoszen** [comment]
Wow, that was fast!
