### ISSUE TITLE
Add support for getting an object's Class

### ISSUE THREAD

**Issue by cjbrooks12** [jtwig/jtwig#340]
It doesn't seem possible to fetch an object's `Class` object from within a template. `{{ value.class }}`, `{{ value.class() }}`, and `{{ value.getClass() }}` all return objects of type `org.jtwig.value.Undefined`, when I would expect `java.lang.Class`.

**Comment by lyncodev** [comment]
Adding function to allow this. ``{{ class(value) }}``
