### ISSUE TITLE
value in map incorrectly interpreted

### ISSUE THREAD

**Issue by dernasherbrezon** [jtwig/jtwig#355]
Here is test case:
- create a map with the following values:
  - "a" -> `com.example.FormattedGauge` (with method `String getFormat()`)
  - "b" -> `com.example.FormattedCounter` (different class, but with the same method `String getFormat()`) 
- create template:
			          	  {% for key, value in metrics %}
                                                {{ key ~ " -> " ~ value.format }}
			          	  {% endfor %}
- output will be:
  - "a -> formata"
  - "b -> "

Expected:
  - "a -> formata"
  - "b -> formatb"

I did some debugging and found that during second execution (for "b"), jtwig used the same `org.jtwig.reflection.model.java.JavaMethod` which was cached/created during first execution ("a")! And the debug stack trace:

> java.lang.IllegalArgumentException: java.lang.ClassCastException@14d0eb4
> at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.jtwig.reflection.model.java.JavaMethod.invoke(JavaMethod.java:33)
> 	at org.jtwig.property.resolver.MethodPropertyResolver.resolve(MethodPropertyResolver.java:31)

Looks like  `com.example.FormattedGauge.getFormat()` cannot be casted to the `com.example.FormattedCounter`.

**Comment by MaZderMind** [comment]
@dernasherbrezon thank you for your report. Which jTwig-Version are you using?
This sounds exactly like #343 which was fixed in 5.86.0.RELEASE

**Comment by dernasherbrezon** [comment]
Hi @MaZderMind ! Looks like you're right. I was using 5.85.3.RELEASE. Closing this issue.
