### ISSUE TITLE
parent() Not implemented?

### ISSUE THREAD

**Issue by realcnbs** [jtwig/jtwig#60]
Hello. According to the docs i can use parent() inside an overriding block in order to render the extended block. I am getting this error : 

```
Caused by: com.lyncode.jtwig.exception.ParseException: Wrong function syntax
Explanation: Input position (line 8, pos 11):
{{ parent() }}
          ^
```

**Comment by pun-ky** [comment]
+1. Still waiting for 'parent()' . Thank you for Twig in Java :>

**Comment by appcia** [comment]
Is it a chance to implement that missing core feature in nearest time?

**Comment by lyncodev** [comment]
We are pointing to the 4.0 release happening this summer.

**Comment by appcia** [comment]
I will be satisfied even by snapshot but earlier ;)

**Comment by lyncodev** [comment]
@thomas-p-wilson what about this one. Should be easier to implement with the current structure.

**Comment by thomas-p-wilson** [comment]
Indeed. In fact, the parent() function was one of the primary motivators
for my last large changeset. I'm currently working on the extensions
implementation, after which I'm free to implement parent() functionality if
someone doesn't beat me to it.

**Comment by lyncodev** [comment]
I can give a try :dancer:

**Comment by thomas-p-wilson** [comment]
Block hierarchy management is still a pain in the rear. Sorry about that.

**Comment by MaZderMind** [comment]
@lyncodev what exactly is required to bring this feature forward? I'd be willing to "adopt" this PR as this is really a missing key feature.

**Comment by ludovicmartin** [comment]
Congratulations for your work ! It makes transition from PHP world to Java world very easy.

This feature is very important for a project I am going to work on.
Do you plan to implement "parent" shortly?
As MaZderMind said, this is really a missing key feature...

**Comment by lyncodev** [comment]
Thanks to @MaZderMind this is now about to be released

**Comment by ludovicmartin** [comment]
Thank you very much ! :-)

**Comment by cjbrooks12** [comment]
Great work on this, so excited to try it out!

**Comment by lyncodev** [comment]
Here is an example: http://jtwig.org/try/show/596fdf90372a9f2136ce710a
