### ISSUE TITLE
Implement block() function

### ISSUE THREAD

**Issue by realcnbs** [jtwig/jtwig#88]
This one IMO is very important to have, allows a lot of flexibility for re-usability and composition of templates. Used a lot in symfony forms twig extension [here](https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Twig/Resources/views/Form/form_div_layout.html.twig)  which I am considering to port (at least partially) to jtwig as independent module.

http://twig.sensiolabs.org/doc/functions/block.html

I didn't look into code yet for particularly this one, but it feels like it should be some kind of functionality which would insert duplicates into the render objects tree.

**Comment by thomas-p-wilson** [comment]
The `block()` function was implemented in PR #263. Closing.
